#function set.seed allow to keep the same data distribution create by random for the entire script

```{r}
library(mvtnorm)
library(shinystan)
library(tidyverse)
library(dplyr)
library(purrr)
library(brms)
library(tidyr)
```
###############################################################################
# simulated model
###############################################################################

# y = bm0 + um0 + (bm1 + sm1) * h + e
# sd(e) = exp(bv0 + uv0)

# h = bm0 + um0 + e
# sd(e) = exp(bv0 + uv0)

```{r}
model_range <- 1:300 #Set this at the beginning of each session, used to break up total runs over many sessions
n_ind <- 100 #number of individuals
n_obs <- 5 #number of obs per individual
n_tot <- n_ind * n_obs

# Baseline (avg) within individual effects for individuals in trait y
y_bm0 <- 0 #mean value of y (intercept)
y_bmh <- 1 #plasticity of y as function of h (slope)
y_bv0 <- 0 #Variance in trait y (Intercept for residuals) (specialist)

# Effects for individuals in habitat feature h
h_bm0 <- 0 #mean value of h
h_bv0 <- 0 #variance in habitat use


#Variance-Covariance Matrix for between individuals
y_vm <- 0.3 #Variance in mean value of y
y_vs <- 0.1 #Variance in plasticity (slope)
y_vv <- 0.2 #Variance in how much individuals vary in trait y (specialist vs generalist)
h_vm <- 0.3 #Variance in mean value for habitat feature
h_vv <- 0.2 #Variance in how much individuals vary in their habitat use (some use wide area, others stay put)
```

```{r}
#Compile models with few iterations if the file doesn't exist
if (!file.exists("compiled_m_cs.rds")) {
# Fit the causal model with minimal iterations
m_cs_compiled <- brm(
      bf(y ~ h + (1 + h | a | id), sigma ~ 1 + (1 | a | id)) +
      bf(h ~ 1 + (1 | a | id), sigma ~ 1 + (1 | a | id)) +
      set_rescor(FALSE),
    data = data.frame(id = 1, y = 1, h = 1), # Dummy data for initial compile
    chains = 1, iter = 10, cores = 1
  )
  saveRDS(m_cs_compiled, "compiled_m_cs.rds")
}

if (!file.exists("compiled_m_biv_dh.rds")) {
# Fit the bivariate model with minimal iterations if the file doesn't exist
  m_biv_dh_compiled <- brm(
    bf(y ~ 1 + (1 | a | id), sigma ~ 1 + (1 | a | id)) +
      bf(h ~ 1 + (1 | a | id), sigma ~ 1 + (1 | a | id)) +
      set_rescor(TRUE),
    data = data.frame(id = 1, y = 1, h = 1), # Dummy data for initial compile
    chains = 1, iter = 10, cores = 1
  )
  saveRDS(m_biv_dh_compiled, "compiled_m_biv_dh.rds")
}


if (!file.exists("compiled_m_biv.rds")) {
  m_biv_compiled <- brm(
    bf(y ~ 1 + (1 | id)) +
      bf(h ~ 1 + (1 | id)) +
      set_rescor(TRUE),
    data = data.frame(id = 1, y = 1, h = 1), # Dummy data for initial compile
    chains = 1, iter = 10, cores = 1
  )
  saveRDS(m_biv_compiled, "compiled_m_biv.rds")
}


if (!file.exists("compiled_m_univar.rds")) {
  # Fit the univariate model with minimal iterations
  m_univar_compiled <- brm(
    bf(y ~ h + (1 + h | id)),           # Univariate model formula
    data = data.frame(id = 1, y = 1, h = 1),  # Dummy data for initial compile
    chains = 1, iter = 10, cores = 1
  )
  saveRDS(m_univar_compiled, "compiled_m_univar.rds")
}

```

```{r}
set.seed(sample(1:1e6,1))

# Function to simulate a single data set
simulate_dataset <- function(n_ind, n_obs,
                             y_bm0, y_bmh, y_bv0,
                             h_bm0, h_bv0,
                             y_vm, y_vs, y_vv, h_vm, h_vv) {
  
  n_tot <- n_ind * n_obs
  
  sd_i <- diag(sqrt(c(y_vm, y_vs, y_vv, h_vm, h_vv)))
  cor_m <- matrix(0.5, ncol = ncol(sd_i), nrow = nrow(sd_i))
  diag(cor_m) <- 1
  sigma <- sd_i %*% cor_m %*% sd_i
  
  # Individual deviations
  ind <- MASS::mvrnorm(n_ind, rep(0, ncol(sigma)), sigma)
  
  dat <- data.frame(
    id = rep(seq(n_ind), each = n_obs),
    y_um = rep(ind[, 1], each = n_obs),
    y_us = rep(ind[, 2], each = n_obs),
    y_uv = rep(ind[, 3], each = n_obs),
    h_um = rep(ind[, 4], each = n_obs),
    h_uv = rep(ind[, 5], each = n_obs)
  ) %>%
    mutate(
      e_h = rnorm(n_tot, 0, exp(h_bv0 + h_uv)),
      h = h_bm0 + h_um + e_h,
      e_y = rnorm(n_tot, 0, exp(y_bv0 + y_uv)),
      y = y_bm0 + y_um + (y_bmh + y_us) * h + e_y
    )
  
  dat
}

# Generate a list of datasets for multiple runs
datasets <- lapply(model_range, function(i) {
  simulate_dataset(n_ind, n_obs,
                   y_bm0, y_bmh, y_bv0,
                   h_bm0, h_bv0,
                   y_vm, y_vs, y_vv, h_vm, h_vv)
})

for (i in seq_along(model_range)) {
  run_number <- model_range[i]
  dataset <- datasets[[i]]
  
  saveRDS(dataset, file = paste0("dataset_run_", run_number, ".rds"))
}

# Read in the compiled models
m_cs_compiled <- readRDS("compiled_m_cs.rds")
m_biv_dh_compiled <- readRDS("compiled_m_biv_dh.rds")
m_biv_compiled <- readRDS("compiled_m_biv.rds")
m_univar_compiled <- readRDS("compiled_m_univar.rds")

# Update run_models function with full iterations, make sure to check before running
run_models_data_first <- function(dat, i) {
  # Fit models using precompiled code
  m_cs <- update(m_cs_compiled, newdata = dat, chains = 2, cores = 2, iter = 2000, warmup = 1000, thin = 2)
  m_biv_dh <- update(m_biv_dh_compiled, newdata = dat, chains = 2, cores = 2, iter = 2000, warmup = 1000, thin = 2)
  m_biv <- update(m_biv_compiled, newdata = dat, chains = 2, cores = 2, iter = 2000, warmup = 1000, thin = 2)
  m_univar <- update(m_univar_compiled, newdata = dat, chains = 2, cores = 2, iter = 2000, warmup = 1000, thin = 2)
 
   # Save models to RDS files
  saveRDS(m_cs, file = paste0("model_cs_run_", i, ".rds"))
  saveRDS(m_biv_dh, file = paste0("model_biv_dh_run_", i, ".rds"))
  saveRDS(m_biv, file = paste0("model_biv_run_", i, ".rds"))
  saveRDS(m_univar, file = paste0("model_univar_run_", i, ".rds"))
  
  # No return of the model objects themselves, just save them to files
}
```

```{r}
# Now use map to run models on each dataset and return file names
results <- map2(datasets, model_range, function(dat, i) {
  run_models_data_first(dat, i)
  
  # Return the file names for this run
  list(
    causal = paste0("model_cs_run_", i, ".rds"),
    bivariate_dh = paste0("model_biv_dh_run_", i, ".rds"),
    bivariate = paste0("model_biv_run_", i, ".rds"),
    univariate = paste0("model_univar_run_", i, ".rds")
  )
})

# 'results' now contains a list of file paths for all runs
```


```{r}
# Generate file names based on the model_range, make sure to change model_range at the top, to encompass all the rds files available
causal_model_files <- paste0("model_cs_run_", model_range, ".rds")
bivariate_dh_model_files <- paste0("model_biv_dh_run_", model_range, ".rds")
bivariate_model_files <- paste0("model_biv_run_", model_range, ".rds")
univar_model_files <- paste0("model_univar_run_", model_range, ".rds")


```


```{r}
summarize_models <- function(file_list, path="") {
  # Initialize empty lists to hold fixed effects and random effects summaries
  fixed_effects_list <- list()
  random_effects_list <- list()
  
  # Loop through each file in the list, using seq_along to track run numbers
  for (i in seq_along(file_list)) {
    file <- file_list[[i]]
    # Read the model from the .rds file
    model <- readRDS(paste0(path,file))
    
    # Extract fixed effects and add run identifier
    fixed_effects <- as.data.frame(summary(model)$fixed)
    fixed_effects$parameter <- rownames(fixed_effects)
    fixed_effects$run <- i
    fixed_effects_list <- append(fixed_effects_list, list(fixed_effects))
    
    # Extract random effects (SD and correlations) and add run identifier
    random_effects <- as.data.frame(summary(model)$random$id)
    random_effects$parameter <- rownames(random_effects)
    random_effects$run <- i
    random_effects_list <- append(random_effects_list, list(random_effects))
  }
  
  # Combine all fixed and random effects across runs
  all_fixed <- bind_rows(fixed_effects_list)
  all_random <- bind_rows(random_effects_list)
  
  # Compute average summaries for fixed effects
  fixed_effects_combined <- all_fixed %>%
    group_by(parameter) %>%
    summarise(across(Estimate:Tail_ESS, mean, na.rm = TRUE))
  
  # Compute average summaries for random effects
  random_effects_combined <- all_random %>%
    group_by(parameter) %>%
    summarise(across(Estimate:Tail_ESS, mean, na.rm = TRUE))
  
  # Create wide tables for fixed and random effects by run
  fixed_effects_runs_wide <- all_fixed %>%
    select(run, parameter, Estimate) %>%
    pivot_wider(names_from = parameter, values_from = Estimate)
  
  random_effects_runs_wide <- all_random %>%
    select(run, parameter, Estimate) %>%
    pivot_wider(names_from = parameter, values_from = Estimate)
  
  # Return all results: average summaries and run-by-run tables
  list(
    fixed_effects = fixed_effects_combined,
    random_effects = random_effects_combined,
    fixed_effects_by_run = fixed_effects_runs_wide,
    random_effects_by_run = random_effects_runs_wide
  )
}


```

```{r}
causal_summaries <- summarize_models(causal_model_files, path='C:\\Users\\lamkh\\Documents\\Habitat as a trait Proj\\Outputs_100_5\\model_cs_runs\\')

# Access the averaged summaries
fixed_effects_summary <- causal_summaries$fixed_effects
random_effects_summary <- causal_summaries$random_effects
saveRDS(fixed_effects_summary, file = paste0("Cs_fixed_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))
saveRDS(random_effects_summary, file = paste0("Cs_random_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))

# Access the run-by-run tables
fixed_effects_by_run <- causal_summaries$fixed_effects_by_run
random_effects_by_run <- causal_summaries$random_effects_by_run

# View the results
print(fixed_effects_summary)
print(random_effects_summary)
print(fixed_effects_by_run)
print(random_effects_by_run)
```


```{r}
# Summarize the bivariate double hierarchical models
bivariate_dh_summaries <- summarize_models(bivariate_dh_model_files, path ="C:\\Users\\lamkh\\Documents\\Habitat as a trait Proj\\Outputs_100_5\\model_biv_dh_runs\\")

# Access the averaged summaries
fixed_effects_summary_biv_dh <- bivariate_dh_summaries$fixed_effects
random_effects_summary_biv_dh <- bivariate_dh_summaries$random_effects
saveRDS(fixed_effects_summary, file = paste0("biv_dh_fixed_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))
saveRDS(random_effects_summary, file = paste0("biv_dh_random_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))

# Access the run-by-run tables
fixed_effects_by_run_biv_dh <- bivariate_dh_summaries$fixed_effects_by_run
random_effects_by_run_biv_dh <- bivariate_dh_summaries$random_effects_by_run

# View the results
print(fixed_effects_summary_biv_dh)
print(random_effects_summary_biv_dh)
print(fixed_effects_by_run_biv_dh)
print(random_effects_by_run_biv_dh)



```

```{r}
# Summarize the bivariate models
bivariate_summaries <- summarize_models(bivariate_model_files, path='C:\\Users\\lamkh\\Documents\\Habitat as a trait Proj\\Outputs_100_5\\model_biv_runs\\')

# Access the averaged summaries
fixed_effects_summary_biv <- bivariate_summaries$fixed_effects
random_effects_summary_biv <- bivariate_summaries$random_effects
saveRDS(fixed_effects_summary, file = paste0("biv_fixed_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))
saveRDS(random_effects_summary, file = paste0("biv_random_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))

# Access the run-by-run tables
fixed_effects_by_run_biv <- bivariate_summaries$fixed_effects_by_run
random_effects_by_run_biv <- bivariate_summaries$random_effects_by_run

# View the results
print(fixed_effects_summary_biv)
print(random_effects_summary_biv)
print(fixed_effects_by_run_biv)
print(random_effects_by_run_biv)

```

```{r}
# Summarize the univariate model
univariate_summaries <- summarize_models(univar_model_files, path='C:\\Users\\lamkh\\Documents\\Habitat as a trait Proj\\Outputs_100_5\\model_univar_runs\\')

# Access the averaged summaries
fixed_effects_summary_univar <- univariate_summaries$fixed_effects
random_effects_summary_univar <- univariate_summaries$random_effects
saveRDS(fixed_effects_summary, file = paste0("univar_fixed_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))
saveRDS(random_effects_summary, file = paste0("univar_random_effects_summary", n_ind, "ind", n_obs, "obs", ".rds"))

# Access the run-by-run tables
fixed_effects_by_run_univar <- univariate_summaries$fixed_effects_by_run
random_effects_by_run_univar <- univariate_summaries$random_effects_by_run

# View the resultsKeep
print(fixed_effects_summary_univar)
print(random_effects_summary_univar)
print(fixed_effects_by_run_univar)
print(random_effects_by_run_univar)
```

```{r}
#Read the summaries back into R, as long as you've got the saved files

# Define sample size parameters
n_ind <- 100  # Change this to match the saved file
n_obs <- 5  # Change this to match the saved file
path <- "C:\\Users\\lamkh\\Documents\\Habitat as a trait Proj\\Outputs_100_5\\Summaries\\"  # Set the directory where summary files are stored

# Function to read an RDS file with a specified path
read_summary <- function(model, n_ind, n_obs, type, path) {
  file_name <- paste0(model, "_", type, "_summary", n_ind, "ind", n_obs, "obs.rds")
  full_path <- file.path(path, file_name)
  
  if (file.exists(full_path)) {
    readRDS(full_path)
  } else {
    warning(paste("File not found:", full_path))
    NULL
  }
}

# Read the summaries
fixed_effects_summary_cs <- read_summary("cs", n_ind, n_obs, "fixed_effects", path)
random_effects_summary_cs <- read_summary("cs", n_ind, n_obs, "random_effects", path)

fixed_effects_summary_biv_dh <- read_summary("biv_dh", n_ind, n_obs, "fixed_effects", path)
random_effects_summary_biv_dh <- read_summary("biv_dh", n_ind, n_obs, "random_effects", path)

fixed_effects_summary_biv <- read_summary("biv", n_ind, n_obs, "fixed_effects", path)
random_effects_summary_biv <- read_summary("biv", n_ind, n_obs, "random_effects", path)

fixed_effects_summary_univar <- read_summary("univar", n_ind, n_obs, "fixed_effects", path)
random_effects_summary_univar <- read_summary("univar", n_ind, n_obs, "random_effects", path)



```

```{r}
compute_metrics <- function(run_by_run, true_vals) {
  # Convert the wide table to long format.

  long_df <- run_by_run %>%
    pivot_longer(-run, names_to = "parameter", values_to = "Estimate")
  
  # Compute the metrics by parameter.
  metrics <- long_df %>%
    group_by(parameter) %>%
    summarise(
      mean_est = mean(Estimate, na.rm = TRUE),
      bias = mean_est - true_vals[unique(parameter)],
      mse = mean((Estimate - true_vals[unique(parameter)])^2, na.rm = TRUE),
      rmse = sqrt(mse),
      precision = sd(Estimate, na.rm = TRUE)
    )
  
  return(metrics)
}

fix_true_vals <- c(
  y_Intercept = 0,
  y_h = 1,
  sigma_y_Intercept = 0,
  h_Intercept = 0,
  sigma_h_Intercept = 0,
  Intercept = 0,  #Added just for the univariate model
  h = 1  #Added just for the univariate model
)

ran_true_vals <- c(
  `cor(h_Intercept,sigma_h_Intercept)`=0.5,
  `cor(sigma_y_Intercept,h_Intercept)`=0.5,
  `cor(sigma_y_Intercept,sigma_h_Intercept)`=0.5,
  `cor(y_Intercept,h_Intercept)`=0.5,
  `cor(y_Intercept,sigma_h_Intercept)`=0.5,
  `cor(y_Intercept,sigma_y_Intercept)`=0.5,
  `cor(y_Intercept,y_h)`=0.5,
  `cor(y_h,h_Intercept)`=0.5,
  `cor(y_h,sigma_h_Intercept)`=0.5,
  `cor(y_h,sigma_y_Intercept)`=0.5,
  `sd(h_Intercept)`=sqrt(0.3),
  `sd(sigma_h_Intercept)`=sqrt(0.2),
  `sd(sigma_y_Intercept)`=sqrt(0.2),
  `sd(y_Intercept)`=sqrt(0.3),
  `sd(y_h)`=sqrt(0.1),  
  `cor(Intercept,h)` =0.5,
  `sd(Intercept)`=sqrt(0.3),
  `sd(h)` =sqrt(0.1)
  
)



```

```{r}
fix_causal_metrics <- compute_metrics(causal_summaries$fixed_effects_by_run, fix_true_vals)
print(fix_causal_metrics)

ran_causal_metrics <- compute_metrics(causal_summaries$random_effects_by_run, ran_true_vals)
print(ran_causal_metrics)
```

```{r}
fix_bivariate_dh_metrics <- compute_metrics(bivariate_dh_summaries$fixed_effects_by_run, fix_true_vals)
print(fix_bivariate_dh_metrics)

ran_bivariate_dh_metrics <- compute_metrics(bivariate_dh_summaries$random_effects_by_run, ran_true_vals)
print(ran_bivariate_dh_metrics)

```

```{r}
fix_bivariate_metrics <- compute_metrics(bivariate_summaries$fixed_effects_by_run, fix_true_vals)
print(fix_bivariate_metrics)

ran_bivariate_metrics <- compute_metrics(bivariate_summaries$random_effects_by_run, ran_true_vals)
print(ran_bivariate_metrics)

```

```{r}
fix_univariate_metrics <- compute_metrics(univariate_summaries$fixed_effects_by_run, fix_true_vals)
print(fix_univariate_metrics)

ran_univariate_metrics <- compute_metrics(univariate_summaries$random_effects_by_run, ran_true_vals)
print(ran_univariate_metrics)

```

```{r}
library(ggplot2)

# Define the true values
true_values <- c(
  "y_Intercept" = y_bm0,
  "y_h" = y_bmh,
  "sigma_y_Intercept" = y_bv0,
  "h_Intercept" = h_bm0,
  "sigma_h_Intercept" = h_bv0
)

# Function to prepare data for plotting (only fixed effects)
prepare_plot_data <- function(fixed_summary, model_name) {
  fixed_summary %>%
    mutate(model = model_name)
}

# Rename parameters in the univariate model to match other models
univariate_fixed <- univariate_summaries$fixed_effects %>%
  mutate(parameter = recode(parameter,
                            "Intercept" = "y_Intercept",
                            "h" = "y_h"))

# Combine data from all models (only fixed effects)
plot_data <- bind_rows(
  prepare_plot_data(causal_summaries$fixed_effects, "Causal"),
  prepare_plot_data(bivariate_dh_summaries$fixed_effects, "Bivariate DH"),
  prepare_plot_data(bivariate_summaries$fixed_effects, "Bivariate"),
  prepare_plot_data(univariate_fixed, "Univariate") # Using renamed univariate model
)

# Rename columns for compatibility
plot_data <- plot_data %>%
  rename(lower = `l-95% CI`, upper = `u-95% CI`)

# Remove correlation (`cor`) and standard deviation (`sd`) parameters
plot_data <- plot_data %>%
  filter(!grepl("^cor|^sd", parameter))

# Create and display separate plots for each fixed-effect parameter with true values
plot_list <- plot_data %>%
  split(.$parameter) %>%
  map(~ ggplot(.x, aes(x = model, y = Estimate)) +
        geom_point(size = 3) +
        geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
        geom_hline(yintercept = true_values[unique(.x$parameter)], linetype = "dashed", color = "red") + 
        labs(title = unique(.x$parameter), x = "Model", y = "Estimated Value") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
      )

# Display plots
for (p in plot_list) {
  print(p)
}

# Define a file name for saving plots based on sample size
plot_file_name <- paste0("Model_Output_fixed_effects_", n_ind, "ind", n_obs, 'obs', ".rds")

# Save the list of plots
saveRDS(plot_list, file = plot_file_name)


```

```{r}
# Define the true values for standard deviations
true_sd_values <- c(
  "sd(y_Intercept)" = sqrt(y_vm),  # Variance in mean value of y
  "sd(y_h)" = sqrt(y_vs),          # Variance in plasticity (slope)
  "sd(sigma_y_Intercept)" = sqrt(y_vv),  # Variance in residual variation of y
  "sd(h_Intercept)" = sqrt(h_vm),  # Variance in mean value for habitat use
  "sd(sigma_h_Intercept)" = sqrt(h_vv)  # Variance in residual variation of h
)

# Function to prepare SD data for plotting
prepare_sd_plot_data <- function(random_summary, model_name) {
  random_summary %>%
    filter(grepl("^sd", parameter)) %>%  # Keep only standard deviation parameters
    mutate(model = model_name)
}

# Rename SD parameters in the univariate model
univariate_sd <- univariate_summaries$random_effects %>%
  filter(grepl("^sd", parameter)) %>%  # Keep only standard deviation parameters
  mutate(parameter = recode(parameter,
                            "sd(Intercept)" = "sd(y_Intercept)",
                            "sd(h)" = "sd(y_h)"))

# Combine SD data from all models
sd_plot_data <- bind_rows(
  prepare_sd_plot_data(causal_summaries$random_effects, "Causal"),
  prepare_sd_plot_data(bivariate_dh_summaries$random_effects, "Bivariate DH"),
  prepare_sd_plot_data(bivariate_summaries$random_effects, "Bivariate"),
  prepare_sd_plot_data(univariate_sd, "Univariate")  # Using renamed univariate SD parameters
)

# Rename columns for compatibility
sd_plot_data <- sd_plot_data %>%
  rename(lower = `l-95% CI`, upper = `u-95% CI`)

# Create separate plots for each SD parameter with true values
sd_plot_list <- sd_plot_data %>%
  split(.$parameter) %>%
  map(~ ggplot(.x, aes(x = model, y = Estimate)) +
        geom_point(size = 3) +
        geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2) +
        geom_hline(yintercept = true_sd_values[unique(.x$parameter)], linetype = "dashed", color = "red") + 
        labs(title = unique(.x$parameter), x = "Model", y = "Estimated SD") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
      )

# Display plots
for (p in sd_plot_list) {
  print(p)
}

# Define a file name for saving SD plots based on sample size
sd_plot_file_name <- paste0("Model_Output_SD_", n_ind, "ind", n_obs, "obs", ".rds")

# Save the list of SD plots
saveRDS(sd_plot_list, file = sd_plot_file_name)


```
```{r}
library(patchwork)

# Loop through each parameter to create and display plots
for (param in parameter_names) {
  
  # Define a more descriptive plot title
  plot_title <- case_when(
    param == "sigma_y_Intercept" ~ "sigma_y",
    param == "sigma_h_Intercept" ~ "sigma_h",
    TRUE ~ param
  )
  
  # Extract the same parameter from different sample sizes
  plots_to_show <- map(plot_lists, ~ .x[[param]])
  
  # Add sample size titles and adjust theme
  plots_to_show <- imap(plots_to_show, ~ .x +
                          ggtitle(.y) +
                          theme(plot.title = element_text(size = 10),
                                axis.title.y = element_blank(),
                                plot.margin = margin(5, 10, 5, 10)))
  
  # Restore y-axis label only for the first plot in each row
  plots_to_show[[1]] <- plots_to_show[[1]] + theme(axis.title.y = element_text())

  # Combine all plots horizontally
  final_plot <- wrap_plots(plots_to_show, ncol = length(plots_to_show)) + 
    plot_annotation(title = plot_title) & theme(plot.margin = margin(5, 5, 5, 5))

  # Display the final plot
  print(final_plot)
}



```

```{r}
library(patchwork)
library(purrr)

# Define file paths for SD plots
sd_file_paths <- list(
  "50ind10obs" = "C:/Users/lamkh/Documents/Habitat as a trait Proj/Output_figures_all/Model_Output_SD_50ind10obs.rds",
  "100ind10obs" = "C:/Users/lamkh/Documents/Habitat as a trait Proj/Output_figures_all/Model_Output_SD_100ind10obs.rds",
  "100ind5obs" = "C:/Users/lamkh/Documents/Habitat as a trait Proj/Output_figures_all/Model_Output_SD_100ind5obs.rds"
)

# Load all SD plot lists
sd_plot_lists <- map(sd_file_paths, readRDS)

# Loop through each SD parameter to create and display combined plots
for (param in names(sd_plot_lists[[1]])) {

  # Define a more descriptive plot title, renaming parameters as needed
  plot_title <- case_when(
    param == "sd(sigma_h_Intercept)" ~ "sd(sigma_h)",
    param == "sd(sigma_y_Intercept)" ~ "sd(sigma_y)",
    TRUE ~ param
  )

  # Extract the same SD parameter across different sample sizes
  plots_to_show <- map(sd_plot_lists, ~ .x[[param]])

  # Add titles with only sample size (remove parameter name duplication)
  plots_to_show <- map2(plots_to_show, names(sd_plot_lists), 
                        ~ .x +
                          ggtitle(.y) +
                          theme(plot.title = element_text(size = 10),
                                axis.title.y = element_blank(),
                                plot.margin = margin(5, 10, 5, 10)))

  # Restore y-axis label only for the first plot
  plots_to_show[[1]] <- plots_to_show[[1]] + 
    ylab("Estimated SD") + 
    theme(plot.margin = margin(5, 10, 5, 20)) # Extra left space

  # Combine all SD plots in a single row using `patchwork`
  final_plot <- wrap_plots(plots_to_show, ncol = length(plots_to_show)) + 
    plot_annotation(title = plot_title) & theme(plot.margin = margin(5, 5, 5, 5)) 

  # Display the final SD plot
  print(final_plot)
}

```



